const courses = [
    {
        id: 1,
        category: 'Pemula',
        img: 'https://images.unsplash.com/photo-1588106329001-2362b7d964ac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        totalLessons: 20,
        rating: '4',
        title: 'Cara merawat kandang maggot',
        author: 'Tanjiro Kusumo',
        author_img: 'https://randomuser.me/api/portraits/women/55.jpg',
        vip: false,
    },
    {
        id: 1,
        category: 'Pemula',
        img: 'https://images.unsplash.com/photo-1588106329001-2362b7d964ac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        totalLessons: 20,
        rating: '4',
        title: 'Cara merawat kandang maggot',
        author: 'Tanjiro Kusumo',
        author_img: 'https://randomuser.me/api/portraits/women/55.jpg',
        vip: false,
    },
    {
        id: 1,
        category: 'Menengah',
        img: 'https://images.unsplash.com/photo-1588106329001-2362b7d964ac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        totalLessons: 20,
        rating: '4',
        title: 'Cara merawat kandang maggot',
        author: 'Tanjiro Kusumo',
        author_img: 'https://randomuser.me/api/portraits/women/55.jpg',
        vip: false,
    },
    {
        id: 1,
        category: 'Pemula',
        img: 'https://images.unsplash.com/photo-1588106329001-2362b7d964ac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        totalLessons: 14,
        rating: '4',
        title: 'Cara merawat kandang maggot',
        author: 'Tanjiro Kusumo',
        author_img: 'https://randomuser.me/api/portraits/women/55.jpg',
        vip: false,
    },
    {
        id: 1,
        category: 'Pemula',
        img: 'https://images.unsplash.com/photo-1588106329001-2362b7d964ac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        totalLessons: 13,
        rating: '4',
        title: 'Cara merawat kandang maggot',
        author: 'Tanjiro Kusumo',
        author_img: 'https://randomuser.me/api/portraits/women/55.jpg',
        vip: false,
    },
    {
        id: 1,
        category: 'Lanjutan',
        img: 'https://images.unsplash.com/photo-1588106329001-2362b7d964ac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        totalLessons: 21,
        rating: '4',
        title: 'Cara merawat kandang maggot',
        author: 'Tanjiro Kusumo',
        author_img: 'https://randomuser.me/api/portraits/women/55.jpg',
        vip: true,
    },
]

export function getAllCourse() {
    return courses
}